package com.pplus.luckybol;

/**
 * Created by 김종경 on 2016-08-10.
 */
public class Const {

    private static final String BASE_URL = "https://stg-api.prnumber.com/";
//    private static final String BASE_URL = "https://api.prnumber.com/";
    public static final boolean DEBUG_MODE = true;

    public static final String API_URL = BASE_URL + "store/api/";

    public static final int LOAD_DATA_LIMIT_CNT = 20;

    public static boolean onReceivePlus = false;

    //    public static final String YOUTUBE_WATCH_URL_PREFIX = "http://www.youtube.com/watch?v=";

//    public static final String GAL_COM_CODE = "A2820008";

    public static final String APP_TYPE = "luckyball";

    //key
    public static final String KEY = "key";
    public static final String TAB = "tab";
    public static final String PATH = "path";
    public static final String GROUP = "group";
    public static final String LOGIN_ID = "login_id";
    public static final String FIND_ID = "find_id";
    public static final String FIND_PW = "find_pw";
    public static final String FRIEND = "friend";
    public static final String FEED = "feed";
    public static final String VERIFICATION = "verification";
    public static final String VERIFICATION_ME = "verification_me";
    public static final String LATITUDE = "latitude";
    public static final String LONGITUDE = "longitude";
    public static final String PRIORITY = "priority";
    public static final String NO = "no";
    public static final String PAGE = "page";
    public static final String PAGE_SEQ_NO = "page_seq_no";
    public static final String PAGE2 = "page2";
    public static final String MODE = "mode";
    public static final String REPLY = "reply";
    public static final String EVENT_REPLY = "event_reply";
    public static final String REPLY_CHILD = "reply_child";
    public static final String POST = "post";
    public static final String COUPON = "coupon";
    public static final String MOBILE_NUMBER = "mobile_number";
    public static final String GUIDE_PLUS = "guide_plus";
    public static final String GUIDE_MAIN = "guide_home";
    public static final String GUIDE_CUSTOMER = "guide_customer";
    public static final String GUIDE_CONTACT = "guide_contact";
    public static final String GUIDE_SEARCH = "guide_search";
    public static final String GUIDE_PAGE_ME = "guide_page_me";
    public static final String GUIDE_POINT_PAGE = "GUIDE_POINT_PAGE";
    public static final String GUIDE_HOT_DEAL_LIVE = "GUIDE_HOT_DEAL_LIVE";
    public static final String GUIDE_PROFILE_SET = "guide_profile_set";
    public static final String GUIDE_ALL = "guide_all";
    public static final String PLUS_GROUP_ADD = "plus_group_add";
    public static final String PLUS_GROUP_DEL = "plus_group_del";
    public static final String CUSTOMER = "customer";
    public static final String RECOMMEND = "recommend";
    public static final String PARTICIPATEID = "participateID";
    public static final String JOIN = "join";
    public static final String JOIN_DATE = "join_date";
    public static final String JOIN_TERM = "join_term";
    public static final String REMAIN_SECOND = "remain_second";
    public static final String LEAVE = "leave";
    public static final String CANCEL_LEAVE = "cancel_leave";
    public static final String USER = "user";
    public static final String DATA = "data";
    public static final String POINT = "point";
    public static final String POINT_BUY = "point_buy";
    public static final String EVENT_BUY = "event_buy";
    public static final String TERMS_LIST = "terms_list";
    public static final String POSITION = "category_position";
    public static final String CATEGORY = "category";
    public static final String PASSWORD_DEFAULT = "**********";
    public static final String PUSH_DATA = "push_data";
    public static final String NUMBER = "number";
    public static final String CROPPED_IMAGE = "cropped_image";
    public static final String AMOUNT = "amount";
    public static final String PAYMETHOD = "paymethod";
    public static final String GOODS = "goods";
    public static final String GOODS_PRICE = "goods_price";
    public static final String GOODS_HISTORY = "goods_history";
    public static final String NOTICE = "notice";
    public static final String FAQ = "faq";
    public static final String MY = "my";
    public static final String TOTAL = "total";
    public static final String OID = "oid";
    public static final String TID = "tid";
    public static final String PG_TYPE = "pg_type";
    public static final String COUNT = "count";
    public static final String SECRET_KEY = "!@#$QWER";
    public static final String SCHEMA_SEARCH = "schema_search";
    public static final String SCHEMA = "schema";
    public static final String FILTER = "filter";
    public static final String ADVERTISE = "advertise";
    public static final String GET = "get";
    public static final String EVENT_RESULT = "event_result";
    public static final String EVENT_WIN = "event_win";
    public static final String EVENT_WIN_JPA = "event_win_jpa";
    public static final String EVENT_JOIN = "event_join";
    public static final String EVENT_REVIEW = "event_review";
    public static final String OUT_GOING = "out_going";
    public static final String PAD = "pad";
    public static final String SIGN_UP = "sign_up";
    public static final String BIRTH_DAY = "birth_day";
    public static final String ID = "id";
    public static final String PASSWORD = "password";
    public static final String ACCOUNT_TYPE = "account_type";
    public static final String NICKNAME = "nickname";
    public static final String FIRST_USER_POST = "first_user_post";
    public static final String DUPLICATE = "duplicate";
    public static final String TIME = "time";
    public static final String URL = "url";
    public static final String PUSH_ID = "push_id";
    public static final String X = "x";
    public static final String Y = "y";
    public static final String CART = "cart";
    public static final String TERMS1 = "terms1";
    public static final String TERMS2 = "terms2";
    public static final String BUY_GOODS = "buy_goods";
    public static final String PURCHASE_PRODUCT = "purchase_product";
    public static final String EVENT_GUIDE = "event_guide";
    public static final String PLAY_GUIDE = "play_guide";
    public static final String NUMBER_EVENT_GUIDE = "number_event_guide";
    public static final String LOGIN = "login";
    public static final String TUTORIAL = "tutorial";
    public static final String TYPE = "type";
    public static final String MENU = "menu";
    public static final String ADDRESS = "address";
    public static final String CONFIRM_LOTTO = "confirm_lotto";
    public static final String EVENT = "event";
    public static final String LOTTO_TIMES = "lotto_times";
    public static final String LOTTO = "lotto";
    public static final String WIN_CODE = "win_code";
    public static final String LOTTO_GUIDE = "lotto_guide";
    public static final String EXCHANGE = "exchange";
    public static final String START = "start";
    public static final String END = "end";
    public static final String PROFILE = "profile";
    public static final String HOTDEAL = "hotdeal";
    public static final String PLUS = "plus";
    public static final String FAV_TAG = "fav_tag";
    public static final String REFUND = "refund";
    public static final String WARNING = "warning";
    public static final String PAGE_MANAGE = "page_manage";
    public static final String BUY = "buy";
    public static final String INSTALLMENT = "installment";
    public static final String PRICE = "price";
    public static final String ONLY = "only";
    public static final String PROPERTIES = "properties";
    public static final String SCREEN_LOCK = "screen_lock";
    public static final String ZZAL_URL = "zzal_url";
    public static final String ZZAL_ADVERTISE_ID = "zzal_advertise_id";
    public static final String AD_TYPE = "ad_type";
    public static final String IS_FIRST = "is_first";
    public static final String IS_ME = "is_me";
    public static final String NAME = "name";
    public static final String ITEM = "item";
    public static final String DETAIL = "detail";
    public static final String SHIPPING_SITE = "shipping_site";
    public static final String EVENT_GIFT = "event_gift";
    public static final String PRODUCT_PRICE = "product_price";
    public static final String OPTION_TYPE = "option_type";
    public static final String POPUP = "popup";
    public static final String APP_CHANGE_POPUP = "app_change_popup";
    public static final String ATTENDANCE = "attendance";
    public static final String REWARD_AD = "reward_ad";
    public static final String GOOGEL_REVIEW = "google_review";
    public static final String TWITTER = "twitter";
    public static final String TELEGRAM = "telegram";
    public static final String WINNER_COUNT = "winner_count";
    public static final String BUFF = "buff";


    public static final float NEXT_RECYCLERVIEW_MARGIN = 0.8f;

    // webview
    public static final String WEBVIEW_URL = "url";
    public static final String TITLE = "title";
    public static final String TOOLBAR_RIGHT_ARROW = "right_arrow";

    //req
    public static final int REQ_CHANGE_PHONE = 1000;
    public static final int REQ_SIGN_UP = 10012;
    public static final int REQ_LOCATION_CODE = 1002;
    public static final int REQ_GROUP_CONFIG = 1003;
    public static final int REQ_CHANGE_PW = 1004;
    public static final int REQ_RESTRICTION = 1005; // 제재 팝업에서 FAQ키로 이동 뒤에는 메인으로 이동 처리
    public static final int REQ_PG_PURCHASE = 1006;
    public static final int REQ_IMAGE_FILTER = 1007;
    public static final int REQ_SET_PAGE = 1008;
    public static final int REQ_SIGN_UP_PROFILE = 1009;
    public static final int REQ_SEARCH = 1010;
    public static final int REQ_POST = 1011;
    public static final int REQ_PERMISSION = 1012;
    public static final int REQ_CAMERA_PERMISSION = 1013;
    public static final int REQ_CAMERA = 1014;
    public static final int REQ_GALLERY = 1015;
    public static final int REQ_PROFILE_GALLERY = 1016;
    public static final int REQ_IMAGE_DELETE = 1017;
    public static final int REQ_SIGN_IN = 1018;
    public static final int REQ_CASH_CHANGE = 1019;
    public static final int REQ_TUTORIAL = 1020;
    public static final int REQ_FAQ = 1021;
    public static final int REQ_LEAVE_CANCEL = 1022;
    public static final int REQ_LEAVE = 1023;
    public static final int REQ_FIND_ID = 1024;
    public static final int REQ_FIND_PW = 1025;
    public static final int REQ_RE_REG_NUMBER = 1026;
    public static final int REQ_REPLY = 1027;
    public static final int REQ_CONFIG = 1028;
    public static final int REQ_CARD_CONFIG = 1029;
    public static final int REQ_DETAIL = 1030;
    public static final int REQ_EVENT_DETAIL = 1031;
    public static final int REQ_SET_PROFILE = 1032;
    public static final int REQ_NOTICE_DETAIL = 1033;
    public static final int REQ_INTRODUCE_IMAGE_DETAIL = 1034;
    public static final int REQ_ADD_MENU = 1035;
    public static final int REQ_USE = 1036;
    public static final int REQ_PAGE = 1037;
    public static final int REQ_REVIEW = 1038;
    public static final int REQ_ALERT_REVIEW = 1039;
    public static final int REQ_RESULT = 1040;
    public static final int REQ_VERIFICATION = 1041;
    public static final int REQ_BIRTH = 1042;
    public static final int REQ_ALARM = 1043;
    public static final int REQ_JOIN_ALERT = 1044;
    public static final int REQ_MODIFY = 1045;
    public static final int REQ_GOODS = 1046;
    public static final int REQ_GOODS_DETAIL = 1047;
    public static final int REQ_ORDER = 1048;
    public static final int REQ_PAY = 1049;
    public static final int REQ_ORDER_FINISH = 1050;
    public static final int REQ_BUY_CANCEL = 1051;
    public static final int REQ_PLUS = 1052;
    public static final int REQ_CHROME = 1053;
    public static final int REQ_BANNER = 1053;
    public static final int REQ_ALERT = 1054;
    public static final int REQ_COUNT = 1055;
    public static final int REQ_TIME = 1056;
    public static final int REQ_BOL_LACK = 1057;
    public static final int REQ_ExCHANGE = 1058;
    public static final int REQ_INSTALLMENT = 1060;
    public static final int REQ_BUY = 1061;
    public static final int REQ_QR_PAY = 1062;
    public static final int REQ_REG = 1063;
    public static final int REQ_VERIFICATION_CHANGE_PASS = 1064;
    public static final int REQ_CHANGE_PASSWORD = 1065;
    public static final int REQ_CHECK_PASSWORD = 1066;
    public static final int REQ_INPUT_PRICE = 1067;
    public static final int REQ_PLUS_TERMS = 1068;
    public static final int REQ_VERIFICATION_MAIN = 1069;
    public static final int REQ_PRICE_ALERT = 1070;
    public static final int REQ_GOODS_OPTION = 1071;
    public static final int REQ_GOODS_OPTION_DETAIL = 1072;
    public static final int REQ_SEARCH_ADDRESS = 1073;
    public static final int REQ_SELECT_AREA1 = 1074;
    public static final int REQ_SELECT_AREA2 = 1075;
    public static final int REQ_MY_FAVORITE = 1076;
    public static final int REQ_EVENT_WIN_DETAIL = 1077;
    public static final int REQ_UPDATE = 1078;
    public static final int REQ_RANDOM_DETAIL = 1079;
    public static final int REQ_COMPLETE = 1080;
    public static final int REQ_EVENT_REPLY = 1081;
    public static final int REQ_EVENT_REVIEW_REG = 1082;

    public static final int IMAGE_UPLOAD_MAX_COUNT = 10;

    public static final double CHROME_WEB_MEMORY_MIN = 200.0; // 200 MegaByte
    public static final double CHROME_WEB_MEMORY_MAX = 1000.0; // 최소 1G 이상인 경우

    public static String ADMOB_ID = "ca-app-pub-6932639067773475~3641848105";
    public static String ADMOB_INTERSTITIAL_ID = "ca-app-pub-6932639067773475/8511031402";
    public static String ADMOB_REWARD_ID = "ca-app-pub-6932639067773475/3866797477";

}
