package com.lejel.wowbox.core.network.model.dto

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * Created by imac on 2018. 2. 9..
 */
@Parcelize
class Event(var seqNo: Long? = null,
            var title: String? = null,
            var status: String? = null,
            var primaryType: String? = null,
            var secondaryType: String? = null,
            var winAnnounceType: String? = null,
            var startDatetime: String? = null,
            var endDatetime: String? = null,
            var displayStartDatetime: String? = null,
            var displayEndDatetime: String? = null,
            var android: Boolean? = null,
            var ios: Boolean? = null,
            var contentsType: String? = null,
            var contents: String? = null,
            var joinType: String? = null,
            var joinLimitCount: Int? = null,
            var joinTerm: Int? = null,
            var reward: Int? = null,
            var gift: Boolean? = null,
            var joinCount: Int? = null,
            var minJoinCount: Int? = null,
            var maxJoinCount: Int? = null,
            var winnerCount: Int? = null,
            var totalGiftCount: Int? = null,
            var code: String? = null,
            var displayTimeType: String? = null,
            var path: String? = null,
            var moveType: String? = null,
            var moveTargetString: String? = null,
            var moveTargetNumber: String? = null,//4: 오프라인상품, 5: 온라인상
            var winAnnounceDatetime: String? = null,
            var winnerDesc: String? = null,
            var winPushType: String? = null,
            var winPushTitle: String? = null,
            var winPushBody: String? = null,
            var moveMethod: String? = null,
            var winnerAlert: String? = null,
            var virtualNumber: String? = null,
            var rewardType: String? = null,
            var eventProp: HashMap<String, String>? = null,
            var etc: String? = null,
            var priority: Int? = null,
            var man: Boolean? = null,
            var woman: Boolean? = null,
            var age10: Boolean? = null,
            var age20: Boolean? = null,
            var age30: Boolean? = null,
            var age40: Boolean? = null,
            var age50: Boolean? = null,
            var age60: Boolean? = null,
            var married: Boolean? = null,
            var notMarried: Boolean? = null,
            var hasChild: Boolean? = null,
            var noChild: Boolean? = null,
            var allAddress: Boolean? = null,
            var regDatetime: String? = null,
            var groupSeqNo: Long? = null,
            var winCode: String? = null,
            var appType: String? = null,
            var bannerImageUrl: String? = null,
            var winImageUrl: String? = null,
            var totalGiftImageUrl: String? = null,
            var eventLink: String? = null,
            var agreement: Int? = null,//0:미동의 1:동의 2: 한방에
            var deliveryInfo: Boolean? = null,
            var isDb: Boolean? = null,
            var detailType: Int? = null,//1:상세없음 2:url 3:자체상세
            var detailTitle: String? = null,
            var detailExplain: String? = null,
            var personalTitle: String? = null,
            var personalContents: String? = null,
            var campaignSeqNo: Long? = null,
            var useDetailItem: Boolean? = null,
            var mainBannerImage: String? = null,
            var eventDetailImage: String? = null,
            var mainBannerDisplay: Boolean? = null,
            var mainBannerArray: Int? = null,
            var liveUrl: String? = null,
            var winAnnounceUrl: String? = null,
            var hint: String? = null,
            var lastJoinDatetime: String? = null,
            var eventTime: List<EventTime>? = null,
            var eventGift: List<EventGift>? = null) : Parcelable {}