package com.pplus.prnumberuser.core.network.model.dto

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * Created by imac on 2018. 2. 9..
 */
@Parcelize
class Event(var no: Long? = null,
            var title: String? = null,
            var code: String? = null,
            var status: String? = null,
            var primaryType: String? = null,
            var secondaryType: String? = null,
            var winAnnounceType: String? = null,
            var winSelectType: String? = null,
            var duration: Duration? = null,
            var aos: Boolean? = null,
            var ios: Boolean? = null,
            var joinType: String? = null,
            var joinLimitCount: Int? = null,
            var joinTerm: Int? = null,
            var reward: Int? = null,
            var rewardType: String? = null,
            var gift: Boolean? = null,
            var bizType: String? = null,
            var displayUserApp: Boolean? = null,
            var displayBizApp: Boolean? = null,
            var adType: String? = null,
            var adRegistType: String? = null,
            var adRegistCount: Int? = null,
            var adPrice: Int? = null,
            var targetType: String? = null,
            var joinCount: Int? = null,
            var winnerCount: Int? = null,
            var bannerPageView: Int? = null,
            var bannerUserView: Int? = null,
            var moveType: String? = null,
            var moveMethod: String? = null,
            var etc: String? = null,
            var priority: Int? = null,
            var man: Boolean? = null,
            var woman: Boolean? = null,
            var age10: Boolean? = null,
            var age20: Boolean? = null,
            var age30: Boolean? = null,
            var age40: Boolean? = null,
            var age50: Boolean? = null,
            var age60: Boolean? = null,
            var married: Boolean? = null,
            var notMarried: Boolean? = null,
            var hasChild: Boolean? = null,
            var noChild: Boolean? = null,
            var regDate: String? = null,
            var virtualNumber: String? = null,
            var displayTimeList: List<Duration>? = null,
            var contentsType: String? = null,
            var contents: String? = null,
            var moveTargetString: String? = null,
            var moveTargetNumber: Int? = null,//4: 오프라인상품, 5: 온라인상
            var winAnnounceDate: String? = null,
            var winnerAlert: String? = null,
            var minJoinCount: Int? = null,
            var maxJoinCount: Int? = null,
            var totalGiftCount: Int? = null,
            var winCode: String? = null,
            var lottoPrice: Int? = null,
            var lottoMatchNum: Int? = null,
            var lottoTimes: String? = null,
            var pageSeqNo: Long? = null,
            var rewardPlay: Int? = null,
            var buyType: String? = null,
            var buyLimitCount: Int? = null,
            var winAnnounceRandomDatetime: String? = null,
            var lastJoinDatetime: String? = null,
            var bannerImageUrl: String? = null,
            var winImageUrl: String? = null,
            var totalGiftImageUrl: String? = null,
            var earnedPoint: Long? = null,
            var groupSeqNo: Long? = null,
            var eventLink: String? = null,
            var isPlus: Boolean? = null,
            var isDb: Boolean? = null,
            var agreement2: Int? = null,//0:미동의 1:동의 2: 한방에
            var deliveryInfo: Boolean? = null,
            var detailType: Int? = null,//1:상세없음 2:url 3:자체상세
            var detailTitle: String? = null,
            var detailExplain: String? = null,
            var personalTitle: String? = null,
            var personalContents: String? = null,
            var campaignSeqNo: Long? = null,
            var useDetailItem: Boolean? = null,
            var joinList: List<LottoEventJoin>? = null) : Parcelable {
}