package com.pplus.prnumberuser.core.network.model.dto

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * Created by imac on 2018. 1. 15..
 */
@Parcelize
class Page(var no: Long? = null,
           var status: String? = null,
           var nickname: String? = null,
           var type: String? = null,
           var name: String? = null,
           var phone: String? = null,
           var openBound: String? = null,
           var homepageLink: String? = null,
           var catchphrase: String? = null,
           var categoryText: String? = null,
           var todayViewCount: Int? = null,
           var totalViewCount: Int? = null,
           var blind: Boolean = false,
           var talkRecvBound: String? = null,
           var talkDenyDay: String? = null,
           var talkDenyStartTime: String? = null,
           var talkDenyEndTime: String? = null,
           var latitude: Double? = null,
           var longitude: Double? = null,
           var distance: Double? = null,
           var customerCount: Int? = null,
           var plusCount: Int? = null,
           var valuationCount: Int? = null,
           var valuationPoint: Int? = null,
           var prBoard: No? = null,
           var reviewBoard: No? = null,
           var address: Address? = null,
           var properties: PageProperties? = null,
           var numberList: List<VirtualNumberManage>? = null,
           var searchKeyword: String? = null,
           var introduction: String? = null,
           var code: String? = null,
           var mainMovieUrl: String? = null,
           var cooperation: No? = null,
           var coopStatus: String? = null,
           var user: User? = null,
           var authCode: String? = null,
           var plus: Boolean? = null,
           var mainGoodsSeqNo: Long? = null,
           var reviewCount: Int? = null,
           var goodsCount: Int? = null,
           var avgEval: Float? = null,
           var isLink: Boolean? = null,
           var hashtag: String? = null,
           var virtualPage: Boolean? = null,
           var isShopOrderable: Boolean? = null,
           var isPackingOrderable: Boolean? = null,
           var isDeliveryOrderable: Boolean? = null,
           var management: PageManagement? = null,
           var isParkingAvailable: Boolean? = null,
           var isValetParkingAvailable: Boolean? = null,
           var usePrnumber: Boolean? = null,
           var distributorAgentCode: String? = null,
           var isSeller: Boolean? = null,
           var isBrand: Boolean? = null,
           var bank: String? = null,
           var bankAccount: String? = null,
           var depositor: String? = null,
           var reason: String? = null,
           var email: String? = null,
           var licenseImage: String? = null,
           var ableNfc: Boolean? = null,
           var shopCode: String? = null,
           var openHours: String? = null,
           var holiday: String? = null,
           var thumbnail: String? = null,
           var goodsNotiType: String? = null,
           var goodsNotification: String? = null,
           var point: Float? = null,
           var woodongyi: Boolean? = null,
           var qrImage: String? = null,
           var storeType: String? = null,
           var categoryMinorSeqNo: Long? = null,
           var categoryMajorSeqNo: Long? = null,
           var deliveryFee: Int? = null,
           var refundDeliveryFee: Int? = null,
           var deliveryAddFee: Int? = null,
           var deliveryMinPrice: Int? = null,
           var pageOperatorType: String? = null,
           var area: String? = null,
           var backgroundImageUrl: String? = null,
           var plusImage: String? = null,
           var plusInfo: String? = null,
           var shoppingMall: String? = null,
           var marketType: String? = null,
           var businessLicense: BusinessLicense? = null,
           var mainProductPriceSeqNo:Long? = null,
           var noneStatus:String? = null,
           var noneResultStatus:String? = null,
           var noneReason:String? = null,
           var snsPoint:Int? = null,
           var visitPoint:Int? = null,
           var useSns:Boolean? = null,
           var benefit:String? = null,
           var echossId:String? = null,
           var visitMinPrice:Int? = null) : Parcelable {
}