package com.pplus.prnumberuser.core.network.model.dto

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * Created by imac on 2018. 1. 15..
 */
@Parcelize
class Page2(var seqNo: Long? = null,
            var memberSeqNo: Long? = null,
            var coopSeqNo: Long? = null,
            var status: String? = null,
            var name: String? = null,
            var phone: String? = null,
            var openBound: String? = null,
            var zipCode: String? = null,
            var roadAddress: String? = null,
            var roadDetailAddress: String? = null,
            var parcelAddress: String? = null,
            var parcelDetailAddress: String? = null,
            var latitude: Double? = null,
            var longitude: Double? = null,
            var catchphrase: String? = null,
            var categoryText: String? = null,
            var todayViewCount: Int? = null,
            var totalViewCount: Int? = null,
            var blind: Boolean = false,
            var talkRecvBound: String? = null,
            var talkDenyDay: String? = null,
            var talkDenyStartTime: String? = null,
            var talkDenyEndTime: String? = null,
            var customerCount: Int? = null,
            var plusCount: Int? = null,
            var pageProp: String? = null,
            var regDatetime: String? = null,
            var modDatetime: String? = null,
            var type: String? = null,
            var modifierSeqNo: Long? = null,
            var profileSeqNo: Long? = null,
            var profileAttachment: Attachment? = null,
            var bgSeqNo: Long? = null,
            var valuationCount: Int? = null,
            var valuationPoint: Int? = null,
            var offerLimitDate: String? = null,
            var virtualPage: String? = null,
            var searchKeyword: String? = null,
            var code: String? = null,
            var introduction: String? = null,
            var mainMovieUrl: String? = null,
            var coopStatus: String? = null,
            var pageLevel: Int? = null,
            var authCode: String? = null,
            var incorrectAuthCodeCount: Int? = null,
            var agentSeqNo: Long? = null,
            var recommendationCode: String? = null,
            var settlementUrl: String? = null,
            var distance: Double? = null,
            var reviewCount: Int? = null,
            var goodsCount: Int? = null,
            var avgEval: Float? = null,
            var homepageLink: String? = null,
            var isLink: Boolean? = null,
            var plus: Boolean? = null,
            var hashtag: String? = null,
            var numberList: List<PRNumber2>? = null,
            var isShopOrderable: Boolean? = null,
            var isPackingOrderable: Boolean? = null,
            var isDeliveryOrderable: Boolean? = null,
            var management: PageManagement? = null,
            var usePrnumber: Boolean? = null,
            var distributorAgentCode: String? = null,
            var isSeller: Boolean? = null,
            var isBrand: Boolean? = null,
            var bank: String? = null,
            var bankAccount: String? = null,
            var depositor: String? = null,
            var reason: String? = null,
            var email: String? = null,
            var licenseImage: String? = null,
            var ableNfc: Boolean? = null,
            var shopCode: String? = null,
            var openHours: String? = null,
            var holiday: String? = null,
            var thumbnail: String? = null,
            var isParkingAvailable: Boolean? = null,
            var isValetParkingAvailable: Boolean? = null,
            var goodsNotiType: String? = null,
            var goodsNotification: String? = null,
            var point: Float? = null,
            var woodongyi: Boolean? = null,
            var qrImage: String? = null,
            var storeType: String? = null,
            var categoryMinorSeqNo: Long? = null,
            var categoryMajorSeqNo: Long? = null,
            var deliveryFee: Int? = null,
            var refundDeliveryFee: Int? = null,
            var deliveryAddFee: Int? = null,
            var deliveryMinPrice: Int? = null,
            var pageOperatorType: String? = null,
            var area: String? = null,
            var backgroundImage: String? = null,
            var plusImage: String? = null,
            var plusInfo: String? = null,
            var shoppingMall: String? = null,
            var marketType: String? = null,
            var businessLicense: BusinessLicense? = null,
            var noneStatus:String? = null,
            var noneResultStatus:String? = null,
            var noneReason:String? = null,
            var snsPoint:Int? = null,
            var visitPoint:Int? = null,
            var useSns:Boolean? = null,
            var benefit:String? = null,
            var echossId:String? = null,
            var visitMinPrice:Int? = null,
            var riderFee:Int? = null,
            var riderMinFee:Int? = null,
            var riderDistance:Float? = null,
            var riderAreaType:String? = null,
            var businessHoursType:Int? = null,//1:매일(일~토 7개) 2:평일/주말(일~토 7개) 3:요일별(일~토 7개) 4:24시간영업
            var orderType:String? = null,
            var minOrderPrice:Float? = null,
            var cookingTime:Int? = null,
            var riderFreePrice:Float? = null,
            var origin:String? = null,
            var orderInfo:String? = null,
            var isBusinessHour:Boolean? = null,
            var isDayOff:Boolean? = null,
            var isTimeOff:Boolean? = null,
            var orderable:Boolean? = null,
            var riderMappingResult:String? = null,
            var riderType:Int? = null,//1:배달대행사, 2:자체배달, 3:모두사용
            var addRiderFeeDistance:Float? = null,
            var addRiderFee:Float? = null,
            var businessCategory:String? = null,// service, restaurant
            var visitBenefitType:String? = null,// discount, free, none
            var visitBenefit:String? = null,
            var pageBusinessHoursList: List<PageBusinessHours>? = null,
            var pageDayOffList: List<PageDayOff>? = null,
            var pageTimeOffList: List<PageTimeOff>? = null,
            var productPriceList: List<ProductPrice>? = null,
            var prepaymentList: List<Prepayment>? = null,
            var prepaymentPublishList: List<PrepaymentPublish>? = null,
            var totalProductPriceElements:Int? = null,
            var categoryMajor: CategoryMajor? = null,
            var categoryMinor: CategoryMinor? = null) : Parcelable {

    override fun equals(other: Any?): Boolean {
        if (other == null) return false

        return if (other is Page2) {
            other.seqNo == seqNo
        } else {
            false
        }
    }
}